[package]
name = "uasm"
version = "1.0.0"
edition = "2024"
description = "A library for Cargo build scripts for providing the UASM assembler."
authors = ["UnladenCoconut <unladencoconut@gmail.com>", "John Hankinson", "Branislav Habus" ]

[dependencies]

[build-dependencies]
cc = "1.2.38"
